spring.application.name=barber-reservation

# PostgreSQL Baglanti Ayarlari (Docker portumuz: 5433)
spring.datasource.url=jdbc:postgresql://localhost:5433/barberdb
spring.datasource.username=barberuser
spring.datasource.password=barberpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Ayarlari
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Sunucu Portu
server.port=8080
